wandb_version: 1

adaptive_schedule:
  value: false
batch_size:
  value: 8
dropout:
  value: 0.1
gnn_hidden_dim:
  value: 128
gnn_out_dim:
  value: 64
lam_ent_yb:
  value: 0.2
lambda_causal_suf:
  value: 2
lambda_mask_dis:
  value: 0.05
lambda_mask_l1:
  value: 0.05
lambda_maskmean:
  value: 0.2
lambda_maskstd:
  value: 0.1
lambda_ortho:
  value: 0
lambda_pfs:
  value: 0.5
lambda_pfs_attr:
  value: 0.2
lambda_sensitive:
  value: 0.05
lambda_supcon:
  value: 0.05
lr:
  value: 0.0001455956855015139
mask_dis_mode:
  value: norm_overlap
mask_hidden_dim:
  value: 64
mask_target_mean:
  value: 0.1
mask_target_std:
  value: 0.3
mask_temperature:
  value: 2
mask_topk_ratio:
  value: 0.05
masker_lr_mult:
  value: 0.5
num_gnn_layers:
  value: 3
sched_decay:
  value: 0.2
sched_grow:
  value: 0.06
sched_patience:
  value: 8
stage1_ratio:
  value: 0.5
stage2_lr_mult:
  value: 0.3
supcon_temperature:
  value: 0.07
two_stage:
  value: false
weight_decay:
  value: 0
