wandb_version: 1

adaptive_schedule:
  value: true
batch_size:
  value: 8
dropout:
  value: 0
gnn_hidden_dim:
  value: 128
gnn_out_dim:
  value: 32
lam_ent_yb:
  value: 0.4
lambda_causal_suf:
  value: 0.5
lambda_mask_dis:
  value: 0.05
lambda_mask_l1:
  value: 0.1
lambda_maskmean:
  value: 0.2
lambda_maskstd:
  value: 0.1
lambda_ortho:
  value: 0.05
lambda_pfs:
  value: 0.5
lambda_pfs_attr:
  value: 0.05
lambda_sensitive:
  value: 0.05
lambda_supcon:
  value: 0.05
lr:
  value: 0.00031141986702271513
mask_dis_mode:
  value: norm_overlap
mask_hidden_dim:
  value: 64
mask_target_mean:
  value: 0.2
mask_target_std:
  value: 0.3
mask_temperature:
  value: 0.5
mask_topk_ratio:
  value: 0.1
masker_lr_mult:
  value: 2
num_gnn_layers:
  value: 4
sched_decay:
  value: 0.1
sched_grow:
  value: 0.02
sched_patience:
  value: 8
stage1_ratio:
  value: 0.5
stage2_lr_mult:
  value: 0.2
supcon_temperature:
  value: 0.1
two_stage:
  value: false
weight_decay:
  value: 0.001
