wandb_version: 1

adaptive_schedule:
  value: false
batch_size:
  value: 8
dropout:
  value: 0.2
gnn_hidden_dim:
  value: 32
gnn_out_dim:
  value: 64
lam_ent_yb:
  value: 0
lambda_causal_suf:
  value: 0.5
lambda_mask_dis:
  value: 0.05
lambda_mask_l1:
  value: 0.2
lambda_maskmean:
  value: 0.05
lambda_maskstd:
  value: 0.1
lambda_ortho:
  value: 0.1
lambda_pfs:
  value: 0.3
lambda_pfs_attr:
  value: 0.05
lambda_sensitive:
  value: 0.05
lambda_supcon:
  value: 0
lr:
  value: 9.875977023447191e-05
mask_dis_mode:
  value: overlap
mask_hidden_dim:
  value: 32
mask_target_mean:
  value: 0.3
mask_target_std:
  value: 0.1
mask_temperature:
  value: 1
mask_topk_ratio:
  value: 0.05
masker_lr_mult:
  value: 2
num_gnn_layers:
  value: 3
sched_decay:
  value: 0.1
sched_grow:
  value: 0.02
sched_patience:
  value: 3
stage1_ratio:
  value: 0.5
stage2_lr_mult:
  value: 0.3
supcon_temperature:
  value: 0.1
two_stage:
  value: false
weight_decay:
  value: 0.001
