name: DisC
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - pytorch==1.7.1
  - torchaudio==0.7.2
  - torchvision==0.8.2
  - ipykernel
prefix: C:\Users\falih\miniconda3\envs\DisC
