wandb_version: 1

adaptive_schedule:
  value: false
batch_size:
  value: 8
disease_pos_weight_mode:
  value: none
dropout:
  value: 0.1
eval_thr_grid:
  value: coarse
eval_thr_mode:
  value: best_acc
eval_use_best_thr:
  value: true
gnn_hidden_dim:
  value: 48
gnn_out_dim:
  value: 32
grad_clip:
  value: 0
lam_ent_yb:
  value: 0.2
lambda_causal_suf:
  value: 0
lambda_mask_dis:
  value: 0.35
lambda_mask_l1:
  value: 0
lambda_maskmean:
  value: 0.3
lambda_maskstd:
  value: 0.05
lambda_ortho:
  value: 0.05
lambda_pfs:
  value: 0.4
lambda_pfs_attr:
  value: 0.05
lambda_sensitive:
  value: 0.08
lambda_supcon:
  value: 0.02
lr:
  value: 0.00039
mask_dis_mode:
  value: norm_overlap
mask_reg_weight:
  value: 0.4
mask_target_mean:
  value: 0.3
mask_target_std:
  value: 0.3
mask_topk_ratio:
  value: 0.05
num_epochs:
  value: 100
num_gnn_layers:
  value: 4
patience:
  value: 30
supcon_temperature:
  value: 0.07
two_stage:
  value: false
warmup_epoch:
  value: 10
weight_decay:
  value: 0.001
