wandb_version: 1

adaptive_schedule:
  value: false
batch_size:
  value: 16
dataset:
  value: ADHD
dropout:
  value: 0.2
folds:
  value: 1
gnn_hidden_dim:
  value: 128
lam_ent_yb:
  value: 0.4
lambda_causal_suf:
  value: 1
lambda_sensitive:
  value: 0.02
lr:
  value: 0.0004845965309512516
mask_dis_mode:
  value: norm_overlap
mask_target_mean:
  value: 0.3
mask_target_std:
  value: 0.3
mask_temperature:
  value: 2
mask_topk_ratio:
  value: 0.2
num_epochs:
  value: 60
num_gnn_layers:
  value: 4
two_stage:
  value: false
warmup_epoch:
  value: 10
weight_decay:
  value: 0.0001
