_wandb:
    value:
        cli_version: 0.23.1
        e:
            52hckebxxjqxjukkm7ccvzaxogmnbtaj:
                args:
                    - --dataset
                    - ADHD
                    - --seed
                    - "3"
                    - --num_epochs
                    - "100"
                    - --warmup_epoch
                    - "10"
                    - --patience
                    - "30"
                    - --batch_size
                    - "8"
                    - --lr
                    - "0.0001"
                    - --weight_decay
                    - "0.0005"
                    - --masker_lr_mult
                    - "1.0"
                    - --grad_clip
                    - "0.0"
                    - --gnn_hidden_dim
                    - "64"
                    - --gnn_out_dim
                    - "64"
                    - --num_gnn_layers
                    - "2"
                    - --dropout
                    - "0.0"
                    - --num_feats
                    - "116"
                    - --num_classes
                    - "2"
                    - --num_sex_classes
                    - "2"
                    - --num_age_classes
                    - "4"
                    - --fixed_thr
                    - "0.5"
                    - --select_by
                    - val_score_bestthr
                    - --eval_thr_mode
                    - best_acc
                    - --eval_thr_grid
                    - coarse
                    - --eval_use_best_thr
                    - --score_f1_beta
                    - "0.5"
                    - --score_fair_alpha
                    - "0.01"
                    - --lambda_task
                    - "1.0"
                    - --lambda_sensitive
                    - "0.02"
                    - --lambda_pfs
                    - "0.3"
                    - --lambda_pfs_attr
                    - "0.1"
                    - --lambda_supcon
                    - "0.02"
                    - --lambda_ortho
                    - "0.05"
                    - --supcon_temperature
                    - "0.07"
                    - --lambda_causal_suf
                    - "1.0"
                    - --lam_ent_yb
                    - "0.1"
                    - --no_cf_detach_zc
                    - --cf_detach_zb_for_disease
                    - --ent_yb_head_only
                    - --disease_pos_weight_mode
                    - none
                    - --freeze_b_after
                    - "25"
                    - --freeze_c_after
                    - "-1"
                    - --mask_reg_weight
                    - "0.6"
                    - --mask_temperature
                    - "1.0"
                    - --mask_hidden_dim
                    - "64"
                    - --mask_target_mean
                    - "0.22"
                    - --lambda_maskmean
                    - "0.3"
                    - --mask_target_std
                    - "0.2"
                    - --lambda_maskstd
                    - "0.0"
                    - --lambda_mask_dis
                    - "0.35"
                    - --mask_dis_mode
                    - norm_overlap
                    - --mask_topk_ratio
                    - "0.1"
                    - --lambda_mask_l1
                    - "0.0"
                    - --two_stage
                    - --stage1_ratio
                    - "0.35"
                    - --stage2_lr_mult
                    - "0.3"
                    - --adaptive_schedule
                    - --w_pfs_init
                    - "0.1"
                    - --w_sup_init
                    - "0.05"
                    - --w_csuf_init
                    - "0.05"
                    - --w_pfs_max
                    - "0.35"
                    - --w_sup_max
                    - "0.25"
                    - --w_csuf_max
                    - "0.2"
                    - --sched_grow
                    - "0.04"
                    - --sched_decay
                    - "0.1"
                    - --sched_patience
                    - "5"
                    - --mask_min_mean
                    - "0.08"
                    - --mask_max_norm_overlap
                    - "1.4"
                    - --out_dir
                    - results
                    - --use_5fold
                    - --fold_id
                    - "3"
                    - --use_wandb
                    - --wandb_project
                    - DisBG
                    - --wandb_entity
                    - mjliujade-federation-university-australia
                    - --wandb_group
                    - ADHD_seed0
                    - --wandb_name
                    - ADHD_fold3_seed3
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 128
                disk:
                    /:
                        total: "32212254720"
                        used: "25430904832"
                email: mjliujade@gmail.com
                executable: /root/miniconda3/envs/disbg/bin/python
                host: autodl-container-9b594ca734-9105cd32
                memory:
                    total: "810178560000"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.17
                program: main.py
                python: CPython 3.8.20
                root: /root/autodl-tmp/DisBG-Jade
                startedAt: "2026-01-02T05:05:06.490942Z"
                writerId: 52hckebxxjqxjukkm7ccvzaxogmnbtaj
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
                - 61
                - 62
            "4": 3.8.20
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
adaptive_schedule:
    value: true
batch_size:
    value: 8
cf_detach_zb_for_disease:
    value: true
cf_detach_zc:
    value: false
dataset:
    value: ADHD
disease_pos_weight:
    value: null
disease_pos_weight_mode:
    value: none
dropout:
    value: 0
ent_yb_head_only:
    value: true
eval_thr_grid:
    value: coarse
eval_thr_mode:
    value: best_acc
eval_use_best_thr:
    value: true
fixed_thr:
    value: 0.5
fold_id:
    value: 3
freeze_b_after:
    value: 25
freeze_c_after:
    value: -1
gnn_hidden_dim:
    value: 64
gnn_out_dim:
    value: 64
grad_clip:
    value: 0
lam_ent_yb:
    value: 0.1
lambda_causal_suf:
    value: 1
lambda_mask_dis:
    value: 0.35
lambda_mask_l1:
    value: 0
lambda_maskmean:
    value: 0.3
lambda_maskstd:
    value: 0
lambda_ortho:
    value: 0.05
lambda_pfs:
    value: 0.3
lambda_pfs_attr:
    value: 0.1
lambda_sensitive:
    value: 0.02
lambda_supcon:
    value: 0.02
lambda_task:
    value: 1
lr:
    value: 0.0001
mask_dis_mode:
    value: norm_overlap
mask_hidden_dim:
    value: 64
mask_max_norm_overlap:
    value: 1.4
mask_min_mean:
    value: 0.08
mask_reg_weight:
    value: 0.6
mask_target_mean:
    value: 0.22
mask_target_std:
    value: 0.2
mask_temperature:
    value: 1
mask_topk_ratio:
    value: 0.1
masker_lr_mult:
    value: 1
num_age_classes:
    value: 4
num_classes:
    value: 2
num_epochs:
    value: 100
num_feats:
    value: 116
num_gnn_layers:
    value: 2
num_sex_classes:
    value: 2
out_dir:
    value: results
patience:
    value: 30
sched_decay:
    value: 0.1
sched_grow:
    value: 0.04
sched_patience:
    value: 5
score_f1_beta:
    value: 0.5
score_fair_alpha:
    value: 0.01
seed:
    value: 3
select_by:
    value: val_score_bestthr
stage1_ratio:
    value: 0.35
stage2_lr_mult:
    value: 0.3
stageB_warmup:
    value: null
supcon_temperature:
    value: 0.07
two_stage:
    value: true
use_5fold:
    value: true
use_wandb:
    value: true
w_csuf_init:
    value: 0.05
w_csuf_max:
    value: 0.2
w_pfs_init:
    value: 0.1
w_pfs_max:
    value: 0.35
w_sup_init:
    value: 0.05
w_sup_max:
    value: 0.25
wandb_entity:
    value: mjliujade-federation-university-australia
wandb_group:
    value: ADHD_seed0
wandb_mode:
    value: null
wandb_name:
    value: ADHD_fold3_seed3
wandb_notes:
    value: null
wandb_project:
    value: DisBG
wandb_tags:
    value: ""
warmup_epoch:
    value: 10
weight_decay:
    value: 0.0005
