wandb_version: 1

adaptive_schedule:
  value: false
batch_size:
  value: 16
dataset:
  value: ABIDE
dropout:
  value: 0.2
folds:
  value: 1
gnn_hidden_dim:
  value: 32
lam_ent_yb:
  value: 0.2
lambda_causal_suf:
  value: 2
lambda_sensitive:
  value: 0.02
lr:
  value: 0.0003806210633926009
mask_dis_mode:
  value: norm_overlap
mask_target_mean:
  value: 0.2
mask_target_std:
  value: 0.2
mask_temperature:
  value: 2
mask_topk_ratio:
  value: 0.2
num_epochs:
  value: 60
num_gnn_layers:
  value: 3
two_stage:
  value: true
warmup_epoch:
  value: 10
weight_decay:
  value: 0.0005
