wandb_version: 1

lambda_mask_l1:
  value: 0.2
lambda_ortho:
  value: 0.02
lambda_pfs:
  value: 0.3
lambda_sensitive:
  value: 0.01
lambda_supcon:
  value: 0.01
lr:
  value: 0.0002866015696454767
mask_target_mean:
  value: 0.1
masker_lr_mult:
  value: 1
weight_decay:
  value: 0.0001
