wandb_version: 1

lambda_mask_l1:
  value: 0.1
lambda_ortho:
  value: 0.05
lambda_pfs:
  value: 0.5
lambda_sensitive:
  value: 0.01
lambda_supcon:
  value: 0.05
lr:
  value: 7.65088579368049e-05
mask_target_mean:
  value: 0.3
masker_lr_mult:
  value: 2
weight_decay:
  value: 0.0005
