wandb_version: 1

lambda_mask_l1:
  value: 0.2
lambda_ortho:
  value: 0
lambda_pfs:
  value: 0.3
lambda_sensitive:
  value: 0.05
lambda_supcon:
  value: 0
lr:
  value: 0.00037264696623495665
mask_target_mean:
  value: 0.3
masker_lr_mult:
  value: 2
weight_decay:
  value: 0.0001
